using Gateway.Application;
using Gateway.Infrastructure;
using Gateway.Infrastructure.Persistence;
using HotChocolate;
using HotChocolate.Execution;
using HotChocolate.Types;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;

namespace Gateway.Presentation.Tests;

/// <summary>
/// Builds the executable schema from the real production wiring.
/// <para>
/// This matters more than it looks: HotChocolate validates the schema when it is first built, not
/// at compile time. An object type that fails to declare an interface field, an unregistered
/// implementation, a filter bound to a property that no longer exists - all of it compiles cleanly
/// and then fails on the first HTTP request. Building the schema in a test moves that failure into
/// the pipeline, where it belongs.
/// </para>
/// </summary>
public class GraphQlSchemaTests
{
    private const string FakeConnectionString =
        "Server=(local);Database=GatewaySchemaTest;Trusted_Connection=True;TrustServerCertificate=True";

    [Fact]
    public async Task SchemaBuildsWithTheExpectedShape()
    {
        await using ServiceProvider provider = BuildProvider();

        ISchemaDefinition schema = await GetSchemaAsync(provider);

        Assert.Equal("Query", schema.QueryType.Name);

        // The polymorphic root and its three implementations.
        IInterfaceTypeDefinition metricReading =
            schema.Types.GetType<IInterfaceTypeDefinition>("MetricReading");

        Assert.True(metricReading.Fields.ContainsName("type"));
        Assert.True(metricReading.Fields.ContainsName("ingestedAt"));
        Assert.True(metricReading.Fields.ContainsName("receivedAt"));

        foreach (string implementation in new[] { "EnergyReading", "AirQualityReading", "MotionReading" })
        {
            IObjectTypeDefinition objectType =
                schema.Types.GetType<IObjectTypeDefinition>(implementation);

            Assert.Contains(objectType.Implements, i => i.Name == "MetricReading");
            Assert.True(objectType.Fields.ContainsName("receivedAt"));
        }

        // Payload fields land on the right implementation and nowhere else.
        Assert.True(schema.Types.GetType<IObjectTypeDefinition>("EnergyReading")
            .Fields.ContainsName("energyAmount"));
        Assert.True(schema.Types.GetType<IObjectTypeDefinition>("AirQualityReading")
            .Fields.ContainsName("co2"));
        Assert.True(schema.Types.GetType<IObjectTypeDefinition>("MotionReading")
            .Fields.ContainsName("isMotionDetected"));

        // Types generated by the paging, filtering and sorting middleware.
        Assert.True(schema.Types.ContainsName("MetricReadingsCollectionSegment"));
        Assert.True(schema.Types.ContainsName("MetricReadingFilterInput"));
        Assert.True(schema.Types.ContainsName("MetricReadingSortInput"));
    }

    [Fact]
    public async Task FilterAndSortSurfacesAreRestrictedToTheAllowlist()
    {
        await using ServiceProvider provider = BuildProvider();

        ISchemaDefinition schema = await GetSchemaAsync(provider);

        IInputObjectTypeDefinition filter =
            schema.Types.GetType<IInputObjectTypeDefinition>("MetricReadingFilterInput");

        // Renamed to match the output field, and deliberately excludes id.
        Assert.True(filter.Fields.ContainsName("type"));
        Assert.True(filter.Fields.ContainsName("receivedAt"));
        Assert.True(filter.Fields.ContainsName("room"));
        Assert.False(filter.Fields.ContainsName("id"));
        Assert.False(filter.Fields.ContainsName("readingType"));
    }

    [Fact]
    public async Task ReadingTypeEnumHidesTheWritersUnusedNoneMember()
    {
        await using ServiceProvider provider = BuildProvider();

        ISchemaDefinition schema = await GetSchemaAsync(provider);

        IEnumTypeDefinition readingType =
            schema.Types.GetType<IEnumTypeDefinition>("MetricReadingType");

        Assert.Contains(readingType.Values, v => v.Name == "ENERGY");
        Assert.Contains(readingType.Values, v => v.Name == "AIR_QUALITY");
        Assert.Contains(readingType.Values, v => v.Name == "MOTION");
        Assert.DoesNotContain(readingType.Values, v => v.Name == "NONE");
    }

    [Fact]
    public void DbContextFactoryIsRegisteredForTheResolversToResolveAtRuntime()
    {
        // Schema building does not cover this: RegisterDbContextFactory resolves the factory
        // lazily, per resolver call, so a missing AddPooledDbContextFactory would only surface on
        // the first query. Asserted separately for that reason.
        using ServiceProvider provider = BuildProvider();

        Assert.NotNull(provider.GetService<IDbContextFactory<MetricsReadDbContext>>());
    }

    private static ServiceProvider BuildProvider()
    {
        IConfiguration configuration = new ConfigurationBuilder()
            .AddInMemoryCollection(new Dictionary<string, string?>
            {
                ["ConnectionStrings:MetricsDb"] = FakeConnectionString,
            })
            .Build();

        IServiceCollection services = new ServiceCollection();

        // Same order as Program.cs: the point of this test is to compose the production graph,
        // so a layer registered there but not here would make it quietly less faithful.
        services.AddApplication(configuration);
        services.AddInfrastructure(configuration);
        services.AddPresentation(configuration);

        return services.BuildServiceProvider();
    }

    private static async Task<ISchemaDefinition> GetSchemaAsync(IServiceProvider provider)
    {
        try
        {
            return await provider.GetSchemaAsync(
                cancellationToken: TestContext.Current.CancellationToken);
        }
        catch (SchemaException exception)
        {
            // Surface every schema error, not just the first - CI output should be actionable.
            string details = string.Join(
                Environment.NewLine,
                exception.Errors.Select(error => "  - " + error.Message));

            throw new InvalidOperationException(
                "GraphQL schema failed to build:" + Environment.NewLine + details,
                exception);
        }
    }
}
