using Gateway.Application;
using Gateway.Application.Interfaces;
using Gateway.Infrastructure;
using Gateway.Infrastructure.Persistence;
using HotChocolate;
using HotChocolate.Execution;
using HotChocolate.Types;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using NSubstitute;

namespace Gateway.Presentation.Tests;

/// <summary>
/// Builds the executable schema from the real production wiring.
/// <para>
/// This matters more than it looks: HotChocolate validates the schema when it is first built, not
/// at compile time. An object type that fails to declare an interface field, an unregistered
/// implementation, a filter bound to a property that no longer exists - all of it compiles cleanly
/// and then fails on the first HTTP request. Building the schema in a test moves that failure into
/// the pipeline, where it belongs.
/// </para>
/// </summary>
public class GraphQlSchemaTests
{
    private const string FakeConnectionString =
        "Server=(local);Database=GatewaySchemaTest;Trusted_Connection=True;TrustServerCertificate=True";

    [Fact]
    public async Task SchemaBuildsWithTheExpectedShape()
    {
        await using ServiceProvider provider = BuildProvider();

        ISchemaDefinition schema = await GetSchemaAsync(provider);

        Assert.Equal("Query", schema.QueryType.Name);

        // The polymorphic root and its three implementations.
        IInterfaceTypeDefinition metricReading =
            schema.Types.GetType<IInterfaceTypeDefinition>("MetricReading");

        Assert.True(metricReading.Fields.ContainsName("type"));
        Assert.True(metricReading.Fields.ContainsName("ingestedAt"));
        Assert.True(metricReading.Fields.ContainsName("receivedAt"));

        foreach (string implementation in new[] { "EnergyReading", "AirQualityReading", "MotionReading" })
        {
            IObjectTypeDefinition objectType =
                schema.Types.GetType<IObjectTypeDefinition>(implementation);

            Assert.Contains(objectType.Implements, i => i.Name == "MetricReading");
            Assert.True(objectType.Fields.ContainsName("receivedAt"));
        }

        // Payload fields land on the right implementation and nowhere else.
        Assert.True(schema.Types.GetType<IObjectTypeDefinition>("EnergyReading")
            .Fields.ContainsName("energyAmount"));
        Assert.True(schema.Types.GetType<IObjectTypeDefinition>("AirQualityReading")
            .Fields.ContainsName("co2"));
        Assert.True(schema.Types.GetType<IObjectTypeDefinition>("MotionReading")
            .Fields.ContainsName("isMotionDetected"));

        // Types generated by the paging, filtering and sorting middleware.
        Assert.True(schema.Types.ContainsName("MetricReadingsCollectionSegment"));
        Assert.True(schema.Types.ContainsName("MetricReadingFilterInput"));
        Assert.True(schema.Types.ContainsName("MetricReadingSortInput"));
    }

    [Fact]
    public async Task ExposesTheDashboardFields()
    {
        await using ServiceProvider provider = BuildProvider();

        ISchemaDefinition schema = await GetSchemaAsync(provider);

        foreach (string field in new[] { "metricReadings", "metricAggregation", "latestReadings", "rooms", "availableRooms" })
        {
            Assert.True(schema.QueryType.Fields.ContainsName(field), $"Query.{field} is missing.");
        }
    }

    [Fact]
    public async Task AggregationInputIsNamedForTheSchemaNotTheClrType()
    {
        await using ServiceProvider provider = BuildProvider();

        ISchemaDefinition schema = await GetSchemaAsync(provider);

        IInputObjectTypeDefinition input =
            schema.Types.GetType<IInputObjectTypeDefinition>("MetricAggregationInput");

        Assert.True(input.Fields.ContainsName("field"));
        Assert.True(input.Fields.ContainsName("groupByRoom"));
        Assert.True(input.Fields.ContainsName("interval"));

        // Grouping by reading type is deliberately absent: the field already determines the type.
        Assert.False(input.Fields.ContainsName("groupByType"));
        Assert.False(schema.Types.ContainsName("MetricAggregationQueryInput"));
    }

    [Fact]
    public async Task AggregationResultCarriesBucketAndStats()
    {
        await using ServiceProvider provider = BuildProvider();

        ISchemaDefinition schema = await GetSchemaAsync(provider);

        IObjectTypeDefinition bucket = schema.Types.GetType<IObjectTypeDefinition>("MetricAggregationBucket");

        Assert.True(bucket.Fields.ContainsName("room"));
        Assert.True(bucket.Fields.ContainsName("bucketStart"));
        Assert.True(bucket.Fields.ContainsName("stats"));

        IObjectTypeDefinition stats = schema.Types.GetType<IObjectTypeDefinition>("NumericStats");

        foreach (string field in new[] { "count", "min", "max", "average", "sum" })
        {
            Assert.True(stats.Fields.ContainsName(field), $"NumericStats.{field} is missing.");
        }

        IObjectTypeDefinition summary = schema.Types.GetType<IObjectTypeDefinition>("RoomSummary");

        Assert.True(summary.Fields.ContainsName("totalReadings"));
        Assert.True(summary.Fields.ContainsName("latestReading"));
        Assert.True(summary.Fields.ContainsName("latestByType"));
    }

    [Fact]
    public async Task AggregationEnumsUseConstantCaseNames()
    {
        await using ServiceProvider provider = BuildProvider();

        ISchemaDefinition schema = await GetSchemaAsync(provider);

        IEnumTypeDefinition field = schema.Types.GetType<IEnumTypeDefinition>("AggregationField");

        Assert.Contains(field.Values, v => v.Name == "ENERGY_AMOUNT");
        Assert.Contains(field.Values, v => v.Name == "MOTION_DETECTED");

        IEnumTypeDefinition interval = schema.Types.GetType<IEnumTypeDefinition>("TimeInterval");

        Assert.Contains(interval.Values, v => v.Name == "MINUTE");
        Assert.Contains(interval.Values, v => v.Name == "DAY");
    }

    [Fact]
    public async Task FilterAndSortSurfacesAreRestrictedToTheAllowlist()
    {
        await using ServiceProvider provider = BuildProvider();

        ISchemaDefinition schema = await GetSchemaAsync(provider);

        IInputObjectTypeDefinition filter =
            schema.Types.GetType<IInputObjectTypeDefinition>("MetricReadingFilterInput");

        // Renamed to match the output field, and deliberately excludes id.
        Assert.True(filter.Fields.ContainsName("type"));
        Assert.True(filter.Fields.ContainsName("receivedAt"));
        Assert.True(filter.Fields.ContainsName("room"));
        Assert.False(filter.Fields.ContainsName("id"));
        Assert.False(filter.Fields.ContainsName("readingType"));
    }

    [Fact]
    public async Task ReadingTypeEnumHidesTheWritersUnusedNoneMember()
    {
        await using ServiceProvider provider = BuildProvider();

        ISchemaDefinition schema = await GetSchemaAsync(provider);

        IEnumTypeDefinition readingType =
            schema.Types.GetType<IEnumTypeDefinition>("MetricReadingType");

        Assert.Contains(readingType.Values, v => v.Name == "ENERGY");
        Assert.Contains(readingType.Values, v => v.Name == "AIR_QUALITY");
        Assert.Contains(readingType.Values, v => v.Name == "MOTION");
        Assert.DoesNotContain(readingType.Values, v => v.Name == "NONE");
    }

    [Fact]
    public void DbContextFactoryIsRegisteredForTheResolversToResolveAtRuntime()
    {
        // Schema building does not cover this: RegisterDbContextFactory resolves the factory
        // lazily, per resolver call, so a missing AddPooledDbContextFactory would only surface on
        // the first query. Asserted separately for that reason.
        using ServiceProvider provider = BuildProvider();

        Assert.NotNull(provider.GetService<IDbContextFactory<MetricsReadDbContext>>());
        Assert.NotNull(provider.GetService<IMetricReadingQueryService>());
    }

    private static ServiceProvider BuildProvider()
    {
        IConfiguration configuration = new ConfigurationBuilder()
            .AddInMemoryCollection(new Dictionary<string, string?>
            {
                ["ConnectionStrings:MetricsDb"] = FakeConnectionString,
            })
            .Build();

        IServiceCollection services = new ServiceCollection();

        // WebApplicationBuilder contributes these two; a bare ServiceCollection does not. The error
        // filter resolves both from the application container when the executor is built, so
        // without them every schema test fails inside GetSchemaAsync rather than in what it tests.
        services.AddLogging();

        IHostEnvironment environment = Substitute.For<IHostEnvironment>();
        environment.EnvironmentName.Returns(Environments.Production);
        services.AddSingleton(environment);

        // Same order as Program.cs: the point of this test is to compose the production graph,
        // so a layer registered there but not here would make it quietly less faithful.
        services.AddApplication(configuration);
        services.AddInfrastructure(configuration);
        services.AddPresentation(configuration);

        return services.BuildServiceProvider();
    }

    private static async Task<ISchemaDefinition> GetSchemaAsync(IServiceProvider provider)
    {
        try
        {
            return await provider.GetSchemaAsync(
                cancellationToken: TestContext.Current.CancellationToken);
        }
        catch (SchemaException exception)
        {
            // Surface every schema error, not just the first - CI output should be actionable.
            string details = string.Join(
                Environment.NewLine,
                exception.Errors.Select(error => "  - " + error.Message));

            throw new InvalidOperationException(
                "GraphQL schema failed to build:" + Environment.NewLine + details,
                exception);
        }
        catch (InvalidOperationException exception)
        {
            // Anything registered into HotChocolate's schema services - error filters, diagnostic
            // listeners - is activated when the executor is built, and a dependency it cannot
            // resolve there surfaces here as a plain InvalidOperationException, not a
            // SchemaException. Without this branch that failure reads as an unrelated crash.
            throw new InvalidOperationException(
                "GraphQL executor failed to build. A service registered into the schema container "
                + "could not be activated - see the inner exception.",
                exception);
        }
    }
}
